#!/usr/bin/env node

var mdns   = require('../../lib/mdns'),
    sys    = require('sys'),
    assert = require('assert');

assert.strictEqual( mdns.udp('osc').toString(), '_osc._udp');

assert.strictEqual( mdns.tcp('http', 'blogapi').toString(), '_http._tcp,_blogapi');
assert.strictEqual( mdns.tcp('http', 'blogapi', 'newblogapi').toString(),
    '_http._tcp,_blogapi,_newblogapi');


// vim: filetype=javascript:
