#!/usr/bin/env node

var mdns   = require('../../lib/mdns'),
    sys    = require('sys'),
    assert = require('assert');

var expectedEventCount = 4;
var eventCount = 0;

var timeout = 5000;
var timeoutId = setTimeout(function() {
  assert.fail("test did not finish within " + (timeout / 1000) + " seconds.");
}, timeout)

var browser = mdns.createBrowser('_node-mdns-test._tcp');

function stopBrowserIfDone() {
  if (eventCount === expectedEventCount) {
    browser.stop();
    clearTimeout(timeoutId);
  }
}

var changedCount = 0;
browser.on('serviceChanged', function(info, flags) {
  assert.strictEqual(typeof flags, 'number');
  assert.strictEqual(typeof info.interfaceIndex, 'number');
  assert.strictEqual(typeof info.serviceName, 'string');
  assert.strictEqual(typeof info.regtype, 'string');
  assert.strictEqual(info.regtype, '_node-mdns-test._tcp.');
  assert.strictEqual(typeof info.replyDomain, 'string');
  assert.strictEqual(info.replyDomain, 'local.');

  changedCount += 1;
  eventCount += 1;
  stopBrowserIfDone();
});

var upCount = 0;
browser.on('serviceUp', function(info, flags) {
  assert.strictEqual(typeof flags, 'number');
  assert.strictEqual(typeof info.interfaceIndex, 'number');
  assert.strictEqual(typeof info.serviceName, 'string');
  assert.strictEqual(typeof info.regtype, 'string');
  assert.strictEqual(info.regtype, '_node-mdns-test._tcp.');
  assert.strictEqual(typeof info.replyDomain, 'string');
  assert.strictEqual(info.replyDomain, 'local.');

  assert.strictEqual(typeof info.fullname, 'string');
  assert.strictEqual(typeof info.host, 'string');
  assert.strictEqual(typeof info.port, 'number');
  assert.strictEqual(info.port, 4321);

  sys.puts(sys.inspect(info));

  upCount += 1;
  eventCount += 1;
  stopBrowserIfDone();
});

var downCount = 0;
browser.on('serviceDown', function(info, flags) {
  assert.strictEqual(typeof flags, 'number');
  assert.strictEqual(typeof info.interfaceIndex, 'number');
  assert.strictEqual(typeof info.serviceName, 'string');
  assert.strictEqual(typeof info.regtype, 'string');
  assert.strictEqual(info.regtype, '_node-mdns-test._tcp.');
  assert.strictEqual(typeof info.replyDomain, 'string');
  assert.strictEqual(info.replyDomain, 'local.');

  downCount += 1;
  eventCount += 1;
  stopBrowserIfDone();
});

browser.start();

process.on('exit', function() {
  assert.ok(changedCount >= 2);
  assert.ok(upCount >= 1);
  assert.ok(downCount >= 1);
});

var ad = mdns.createAdvertisement('_node-mdns-test._tcp', 4321, function(err, info, flags) {
    if (err) throw err;
    setTimeout(function() { ad.stop() }, 500);
});

ad.start();

// vim: filetype=javascript
