#!/bin/bash

DIR=$(dirname $0)
if [[ -z "$DIR" ]]; then
    DIR="."
fi

export AVAHI_COMPAT_NOWARN=1

TOTAL=0
FAILED=0
SUCCESSFUL=0
for t in $(find $DIR/tests/ -type f -name "test-*"); do
    echo -n "running $(basename $t) ... "
    $t;
    if [[ $? != 0 ]]; then
        echo "FAILED ###"
        FAILED=$(($FAILED + 1))
        FAILED_TESTS="$FAILED_TESTS\n\t$(basename $t)"
    else
        echo "ok"
        SUCCESSFUL=$(($SUCCESSFUL + 1))
    fi
    TOTAL=$(($TOTAL + 1))
done

if [[ "$FAILED" -gt 0 ]]; then
    echo "====================================================="
    echo -n "failed tests:"
    echo -e $FAILED_TESTS
    echo -n -e "\a"
fi

echo "====================================================="
echo "total: $TOTAL failed: $FAILED successful: $SUCCESSFUL"

exit $FAILED
