#!/bin/bash

DIR=$(dirname $0)
if [[ -z "$DIR" ]]; then
    DIR="."
fi

TOTAL=0
FAILED=0
SUCCESSFUL=0
for t in $(ls $DIR/tests/test-*); do
    echo -n "running $(basename $t) ... "
    $t;
    if [[ $? != 0 ]]; then
        echo "FAILED ###"
        FAILED=$(($FAILED + 1))
    else
        echo "ok"
        SUCCESSFUL=$(($SUCCESSFUL + 1))
    fi
    TOTAL=$(($TOTAL + 1))
done

echo "====================================================="
echo "total: $TOTAL failed: $FAILED successful: $SUCCESSFUL"

if [[ "$FAILED" -gt 0 ]]; then
    echo -n -e "\a"
fi
exit $FAILED
