#!/usr/bin/env node

var mdns  = require('../lib/new_mdns'),
    assert = require('assert');

var serviceRef = new mdns.capi.DNSServiceRef();

assert.throws(function() {
    mdns.capi.DNSServiceRefSockFD(serviceRef)
});

mdns.capi.DNSServiceRegister(serviceRef, 0, 0, null, "_node-mdns-test._tcp",
    null, null, 4321, null, null, null);

var fd;
assert.doesNotThrow(function() {
    fd = mdns.capi.DNSServiceRefSockFD(serviceRef)
});

assert.strictEqual(serviceRef.fd, fd);

// vim: filetype=javascript:
