#!/usr/bin/env node

var mdns  = require('../lib/mdns'),
    assert = require('assert');

var serviceRef = new mdns.capi.DNSServiceRef();

  mdns.capi.DNSServiceResolve(serviceRef, 0, 0, 'newton.local', '_node-mdns-test._tcp.',
    'local.', function() {}, null);
//assert.doesNotThrow(function() {
//});

//assert.strictEqual(serviceRef.initialized, true);

assert.throws(function() {
  mdns.capi.DNSServiceResolve();
});


// vim: filetype=javascript:
