#!/usr/bin/env node

var path = require('path')
  , fs   = require('fs')
  , ejs  = require('ejs')
  , less = require('less')
  ;

var package_dir = path.join(path.dirname(process.argv[1]), '..')
  , doc_dir = path.join(package_dir, 'doc')
  , package = JSON.parse(fs.readFileSync(path.join(package_dir, 'package.json')))
  , readme_in = path.join(doc_dir, 'README.ejs')
  , readme_out = path.join(package_dir, 'README.textile')
  , options = {
      package: package
    }
  ;

ejs.renderFile(readme_in, options, function(error, str) {
  if (error) {
    console.log(error);
    return;
  }
  if (path.existsSync(readme_out)) {
    fs.chmodSync(readme_out, 0660);
  }
  fs.writeFileSync(readme_out, str);
  fs.chmodSync(readme_out, 0440);
});

// vim: set filetype=javascript :
