#!/usr/bin/env node

var path = require('path');

try {
  var reporter = require('nodeunit').reporters.default;
} catch(e) {
  console.error("module nodeunit not found. Run 'npm link' to install it.");
  process.exit(1);
}

process.chdir(path.join(__dirname, '..'));
reporter.run(['tests_']);

// vim: filetype=javascript :
