#!/usr/bin/env node

process.env.AVAHI_COMPAT_NOWARN = 1

try {
  var nodeunit = require('nodeunit')
    , nopt = require('nopt')
    , path = require('path')
    , mdns_test = require('../lib/mdns_test')
    ;
} catch(e) {
  console.error("dependencies not found. Run 'npm link' to install them.");
  process.exit(1);
}

nodeunit.reporters.quickfix = mdns_test.quickfix;

var formats = Object.getOwnPropertyNames(nodeunit.reporters)
  , knownOptions = { 'help'  : Boolean 
                   , 'format': formats
                   }
  , parsed = nopt(knownOptions)
  ;

process.title = path.basename(__filename);
if (parsed.help) { printHelp(); process.exit(); }
process.chdir(path.join(__dirname, '..'));
nodeunit.reporters[parsed.format || 'default'].run(['tests_']);

function printUsage() {
  console.log('Usage:', process.title,
      Object.getOwnPropertyNames(knownOptions).map(function(o) {
        return '[--' + o + ']'
      }).join(' '));
}

function printHelp() {
  printUsage(); console.log(
'Options:\n\
   --help          Print this help and exit\n\
   --format=<fmt>  Use formatter <fmt>\n\
\n\
Formats:\n\
   ' + formats.join(', ') + '\n\
');

}

// vim: filetype=javascript :
